version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - cd api
  - gradlew.bat assemble --info --no-daemon

test_script:
  - api\gradlew.bat check --info --no-daemon

branches:
  only:
    - master
    - development

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
